// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00xdQBZ3vJ1Yir3R1qeKk78dpT_VFi0Q',
    appId: '1:234863105486:web:f77e8fbf203b10270e879f',
    messagingSenderId: '234863105486',
    projectId: 'fooddelivery-c4d4d',
    authDomain: 'fooddelivery-c4d4d.firebaseapp.com',
    storageBucket: 'fooddelivery-c4d4d.firebasestorage.app',
    measurementId: 'G-DN6W9C83B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdCamku9Mjz-bCIhiRXrzVUxZUbys0mgM',
    appId: '1:234863105486:android:806e880a352a97430e879f',
    messagingSenderId: '234863105486',
    projectId: 'fooddelivery-c4d4d',
    storageBucket: 'fooddelivery-c4d4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdD11FXJdSk0jmXgC_HKp9t7ZfRzmjb7U',
    appId: '1:234863105486:ios:56eab1ad157de67c0e879f',
    messagingSenderId: '234863105486',
    projectId: 'fooddelivery-c4d4d',
    storageBucket: 'fooddelivery-c4d4d.firebasestorage.app',
    iosBundleId: 'com.example.foi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdD11FXJdSk0jmXgC_HKp9t7ZfRzmjb7U',
    appId: '1:234863105486:ios:56eab1ad157de67c0e879f',
    messagingSenderId: '234863105486',
    projectId: 'fooddelivery-c4d4d',
    storageBucket: 'fooddelivery-c4d4d.firebasestorage.app',
    iosBundleId: 'com.example.foi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA00xdQBZ3vJ1Yir3R1qeKk78dpT_VFi0Q',
    appId: '1:234863105486:web:365afde46d99a0f90e879f',
    messagingSenderId: '234863105486',
    projectId: 'fooddelivery-c4d4d',
    authDomain: 'fooddelivery-c4d4d.firebaseapp.com',
    storageBucket: 'fooddelivery-c4d4d.firebasestorage.app',
    measurementId: 'G-YWYZ6FQHFV',
  );
}
